### ISSUE TITLE
Version in "./docker-compose.yml" is unsupported

### ISSUE THREAD

**Issue by kentahikaru** [SensorsIot/IOTstack#100]
Hello,
i'm trying to follow instructions from README.md (or youtube video) but aftter docker-compose up -d (or via menu.sh) i get following error

pi@amalthea: ~/IOTstack $ docker-compose up -d
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
pi@amalthea: ~/IOTstack $ ./menu.sh 
~/IOTstack ~/IOTstack
checking for project update
From https://github.com/SensorsIot/IOTstack
 * branch            master     -> FETCH_HEAD
An update is available for the project
checking docker version
Docker version >= 18.2.0. You are good to go.
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

I am running Raspbian on Raspberry pi 3 B+
pi@amalthea:~/IOTstack $ uname -a
Linux amalthea 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

pi@amalthea:~/IOTstack $ docker -v
Docker version 19.03.12, build 48a6621

my docker-compose.yml (created by menu.sh)
version: '3.6'
services:

  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer/data:/data

  nodered:
    container_name: nodered
    build: ./services/nodered/.
    restart: unless-stopped
    user: "0"
    privileged: true
    env_file: ./services/nodered/nodered.env
    ports:
      - 1880:1880
    volumes:
      - ./volumes/nodered/data:/data

  influxdb:
    container_name: influxdb
    image: "influxdb:latest"
    restart: unless-stopped
    ports:
      - 8086:8086
      - 8083:8083
      - 2003:2003
    env_file:
      - ./services/influxdb/influxdb.env
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
      - ./backups/influxdb/db:/var/lib/influxdb/backup

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    user: "0"
    ports:
      - 3000:3000
    env_file:
      - ./services/grafana/grafana.env
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/log:/var/log/grafana

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    user: "1883"
    ports:
      - "1883:1883"
    volumes:
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
      - ./volumes/mosquitto/pwfile:/mosquitto/pwfile
      - ./services/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./services/mosquitto/filter.acl:/mosquitto/config/filter.acl

I am not familiar with docker.
Please advise. Thank you.

**Comment by Paraphraser** [comment]
On my RPi 4

```
$ uname -a
Linux sec-dev 5.4.51-v7l+ #1327 SMP Thu Jul 23 11:04:39 BST 2020 armv7l GNU/Linux
$ docker -v
Docker version 19.03.12, build 48a6621
$ head -1 docker-compose.yml
version: '3.6'
```

Can't think why a Raspbian update would fix anything but perhaps try `sudo apt update; sudo apt upgrade`.

Also, how did you install docker? I've noticed some strange behaviours that were ultimately traced to docker being installed "by hand" using `apt` rather than via the menu. If you didn't install it via the menu, perhaps try `sudo apt remove docker docker-compose` then run the menu and let it install docker. The menu does it like this:

```
curl -fsSL https://get.docker.com | sh
sudo usermod -G docker -a $USER
sudo usermod -G bluetooth -a $USER
sudo apt install -y docker-compose
```

If neither of those work, I'm at a loss to explain what you're seeing.

**Comment by Paulf007** [comment]
Get the same error from a fresh install. Did the docker install via the menu as well as the upgrade was also done via the menu.

**Comment by Paraphraser** [comment]
OK. I'll try to replicate your problem on a real RPi3B+.

> Spoiler alert: it works for me. I'm hoping that being able to compare/contrast what I did with your process may lead to the "ahah" moment.

#### Starting point:

* Fresh SD card imaged from [Raspberry Pi OS (32-bit) with desktop](https://www.raspberrypi.org/downloads/raspberry-pi-os/):

	```
	2020-05-27-raspios-buster-armhf.zip
	```

If the reason for any particular step in the following seems unclear, you'll probably find the rationale [here](https://gist.github.com/Paraphraser/55643bd660db46716f6c81266905cae8).

> If you do read that gist, please keep in mind that the objective of the gist is to get an RPi4 running on an SSD. You'll have to ignore the bits that talk about cloning the SD to an SSD. The initial setup and the stuff that comes after Raspbian is running on the SSD are the same.

#### Support host

* Permit headless access via ssh and set up WiFi

```
$ touch /Volumes/boot/ssh
$ vi /Volumes/boot/wpa_supplicant.conf
```

* SD card installed in RPi
* Apply power

```
$ ping raspberrypi.local
$ ssh-keygen -R raspberrypi.local
$ ssh-keygen -R 192.168.203.10
$ ssh pi@raspberrypi.local
```

#### RPi 3B+

```
$ sudo raspi-config
```

Set options (including host name of `octopi.local`:

```
1	Change User Password
	⎣ «new password»
2	Network Options
	⎣	N1 Hostname
		⎣ «host name» eg "octopi"
4	Localisation Options
	⎣	I2 Change Timezone
		⎣ «set country and city»
	⎣	I4 Change WLAN Country
		⎣ «two-character upper-case country code» eg "AU"
5	Interfacing Options
	⎣	P3 VNC
		⎣ enable VNC server
6	Advanced Options
	⎣	A5 Resolution
		⎣ (DMT Mode 82 1920x1080 60Hz 16:9)
8	Update
Finish
```

```
$ sudo reboot
```

#### Support host

```
$ ssh-keygen -R raspberrypi.local
$ ssh-keygen -R octopi.local
$ ssh-keygen -R 192.168.203.10
$ ssh pi@octopi.local
```

#### RPi 3B+

```
$ sudo apt update
$ sudo apt dist-upgrade
# note curl, git and wget are needed - already installed on this image
# not all of the following are essential but they are my standard set
$ sudo apt install -y acl sqlite3 subversion dnsutils iperf sysstat iotop
$ sudo vncpasswd -print
$ sudo vi /etc/vnc/config.d/common.custom
$ sudo systemctl restart vncserver-x11-serviced
```

#### Support host

* Launch VNC client
* Connect to vnc://pi@octopi.local
* Follow all prompts
* Accept suggestion to restart

```
$ ping octopi.local
$ ssh pi@octopi.local
```

#### RPi 3B+

```
$ git clone https://github.com/SensorsIot/IOTstack.git ~/IOTstack

Cloning into '/home/pi/IOTstack'...
remote: Enumerating objects: 109, done.
remote: Counting objects: 100% (109/109), done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 2610 (delta 38), reused 61 (delta 15), pack-reused 2501
Receiving objects: 100% (2610/2610), 982.17 KiB | 678.00 KiB/s, done.
Resolving deltas: 100% (1533/1533), done.

$ cd IOTstack/
```

##### About to choose `Install Docker`

```
$ ./menu.sh 

~/IOTstack ~/IOTstack
checking for project update
From https://github.com/SensorsIot/IOTstack
 * branch            master     -> FETCH_HEAD
Project is up to date
docker not installed
Install Docker
# Executing docker install script, commit: 26ff363bcf3b3f5a00498ac43694bf1c7d9ce16c
+ sudo -E sh -c apt-get update -qq >/dev/null
+ sudo -E sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sudo -E sh -c curl -fsSL "https://download.docker.com/linux/raspbian/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sudo -E sh -c echo "deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable" > /etc/apt/sources.list.d/docker.list
+ sudo -E sh -c apt-get update -qq >/dev/null
+ [ -n  ]
+ sudo -E sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
+ sudo -E sh -c docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a6621
 Built:             Mon Jun 22 15:53:41 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a6621
  Built:            Mon Jun 22 15:47:34 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker pi

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
Install docker-compose
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  rpi-eeprom-images
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  cgroupfs-mount golang-docker-credential-helpers python3-cached-property python3-docker python3-dockerpty python3-dockerpycreds python3-docopt python3-jsonschema python3-texttable python3-websocket python3-yaml
Suggested packages:
  python-jsonschema-doc
Recommended packages:
  docker.io
The following NEW packages will be installed:
  cgroupfs-mount docker-compose golang-docker-credential-helpers python3-cached-property python3-docker python3-dockerpty python3-dockerpycreds python3-docopt python3-jsonschema python3-texttable python3-websocket python3-yaml
0 upgraded, 12 newly installed, 0 to remove and 0 not upgraded.
Need to get 915 kB of archives.
After this operation, 3,774 kB of additional disk space will be used.
Get:1 http://mirror.datamossa.io/raspbian buster/main armhf cgroupfs-mount all 1.4 [6,276 B]
Get:2 http://mirror.datamossa.io/raspbian buster/main armhf python3-cached-property all 1.5.1-3 [12.1 kB]
Get:3 http://mirror.datamossa.io/raspbian buster/main armhf golang-docker-credential-helpers armhf 0.6.1-2 [482 kB]
Get:4 http://mirror.datamossa.io/raspbian buster/main armhf python3-dockerpycreds all 0.3.0-1 [5,204 B]           
Get:5 http://mirror.datamossa.io/raspbian buster/main armhf python3-websocket all 0.53.0-1 [36.6 kB]      
Get:6 http://mirror.datamossa.io/raspbian buster/main armhf python3-docker all 3.4.1-4 [77.8 kB]     
Get:7 http://mirror.datamossa.io/raspbian buster/main armhf python3-dockerpty all 0.4.1-1 [10.7 kB]
Get:8 http://mirror.datamossa.io/raspbian buster/main armhf python3-docopt all 0.6.2-2 [19.9 kB]                                                                                                                                                                       
Get:9 http://mirror.datamossa.io/raspbian buster/main armhf python3-jsonschema all 2.6.0-4 [33.5 kB]                                                                                                                                                                   
Get:10 http://mirror.datamossa.io/raspbian buster/main armhf python3-texttable all 1.6.0-1 [10.9 kB]                                                                                                                                                                   
Get:11 http://mirror.datamossa.io/raspbian buster/main armhf python3-yaml armhf 3.13-2 [111 kB]                                                                                                                                                                        
Get:12 http://mirror.datamossa.io/raspbian buster/main armhf docker-compose all 1.21.0-3 [108 kB]                                                                                                                                                                      
Fetched 915 kB in 9s (96.5 kB/s)                                                                                                                                                                                                                                       
Selecting previously unselected package cgroupfs-mount.
(Reading database ... 94332 files and directories currently installed.)
Preparing to unpack .../00-cgroupfs-mount_1.4_all.deb ...
Unpacking cgroupfs-mount (1.4) ...
Selecting previously unselected package python3-cached-property.
Preparing to unpack .../01-python3-cached-property_1.5.1-3_all.deb ...
Unpacking python3-cached-property (1.5.1-3) ...
Selecting previously unselected package golang-docker-credential-helpers.
Preparing to unpack .../02-golang-docker-credential-helpers_0.6.1-2_armhf.deb ...
Unpacking golang-docker-credential-helpers (0.6.1-2) ...
Selecting previously unselected package python3-dockerpycreds.
Preparing to unpack .../03-python3-dockerpycreds_0.3.0-1_all.deb ...
Unpacking python3-dockerpycreds (0.3.0-1) ...
Selecting previously unselected package python3-websocket.
Preparing to unpack .../04-python3-websocket_0.53.0-1_all.deb ...
Unpacking python3-websocket (0.53.0-1) ...
Selecting previously unselected package python3-docker.
Preparing to unpack .../05-python3-docker_3.4.1-4_all.deb ...
Unpacking python3-docker (3.4.1-4) ...
Selecting previously unselected package python3-dockerpty.
Preparing to unpack .../06-python3-dockerpty_0.4.1-1_all.deb ...
Unpacking python3-dockerpty (0.4.1-1) ...
Selecting previously unselected package python3-docopt.
Preparing to unpack .../07-python3-docopt_0.6.2-2_all.deb ...
Unpacking python3-docopt (0.6.2-2) ...
Selecting previously unselected package python3-jsonschema.
Preparing to unpack .../08-python3-jsonschema_2.6.0-4_all.deb ...
Unpacking python3-jsonschema (2.6.0-4) ...
Selecting previously unselected package python3-texttable.
Preparing to unpack .../09-python3-texttable_1.6.0-1_all.deb ...
Unpacking python3-texttable (1.6.0-1) ...
Selecting previously unselected package python3-yaml.
Preparing to unpack .../10-python3-yaml_3.13-2_armhf.deb ...
Unpacking python3-yaml (3.13-2) ...
Selecting previously unselected package docker-compose.
Preparing to unpack .../11-docker-compose_1.21.0-3_all.deb ...
Unpacking docker-compose (1.21.0-3) ...
Setting up python3-cached-property (1.5.1-3) ...
Setting up python3-texttable (1.6.0-1) ...
Setting up python3-docopt (0.6.2-2) ...
Setting up golang-docker-credential-helpers (0.6.1-2) ...
Setting up python3-dockerpycreds (0.3.0-1) ...
Setting up python3-yaml (3.13-2) ...
Setting up python3-jsonschema (2.6.0-4) ...
update-alternatives: using /usr/bin/python3-jsonschema to provide /usr/bin/jsonschema (jsonschema) in auto mode
Setting up cgroupfs-mount (1.4) ...
Setting up python3-websocket (0.53.0-1) ...
update-alternatives: using /usr/bin/python3-wsdump to provide /usr/bin/wsdump (wsdump) in auto mode
Setting up python3-dockerpty (0.4.1-1) ...
Setting up python3-docker (3.4.1-4) ...
Setting up docker-compose (1.21.0-3) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for systemd (241-7~deb10u4+rpi1) ...
Connection to octopi closed by remote host.
Connection to octopi closed.
```

#### Support host

```
$ ping octopi.local
$ ssh pi@octopi.local
```

#### RPi 3B+

```
$ cd IOTstack/
```

##### About to choose `Build Stack` to select:

* Portainer
* Node-Red
* InfluxDB
* Grafana
* Eclipse-Mosquitto

and, within `Node-Red`, the defaults plus `SQLite`.

```
$ ./menu.sh 

~/IOTstack ~/IOTstack
checking for project update
From https://github.com/SensorsIot/IOTstack
 * branch            master     -> FETCH_HEAD
Project is up to date
checking docker version
Docker version >= 18.2.0. You are good to go.
Adding portainer container
...pulled full portainer from template
Adding nodered container
...pulled full nodered from template
Adding influxdb container
...pulled full influxdb from template
Adding grafana container
...pulled full grafana from template
Adding mosquitto container
...pulled full mosquitto from template
...Running directoryfix.sh on mosquitto
...found user 1883
no override found, using docker-compose.yml
docker-compose successfully created
run 'docker-compose up -d' to start the stack

$ docker-compose up -d

Creating network "iotstack_default" with the default driver
Pulling portainer (portainer/portainer:)...
latest: Pulling from portainer/portainer
d1e017099d17: Pull complete
234a6318dcdf: Pull complete
Digest: sha256:f8c2b0a9ca640edf508a8a0830cf1963a1e0d2fd9936a64104b3f658e120b868
Status: Downloaded newer image for portainer/portainer:latest
Building nodered
Step 1/3 : FROM nodered/node-red:latest
latest: Pulling from nodered/node-red
3cfb62949d9d: Pull complete
7196fa1baa84: Pull complete
ffa1a995044c: Pull complete
f2c1d269ddbb: Pull complete
dc8e31e96884: Pull complete
2f620db97fc0: Pull complete
ff155582279f: Pull complete
641aa841f504: Pull complete
79b7f3c19524: Pull complete
075079fbadc9: Pull complete
edffea85e9b5: Pull complete
Digest: sha256:ae6903b431b94559c5f3f1204a39816ece04bd290378962716b9c8b15e88f46c
Status: Downloaded newer image for nodered/node-red:latest
 ---> b7b447a3e061
Step 2/3 : RUN for addonnodes in node-red-node-pi-gpiod node-red-dashboard node-red-contrib-influxdb node-red-contrib-boolean-logic node-red-node-rbe node-red-configurable-ping node-red-node-email ; do npm install ${addonnodes} ;done;
 ---> Running in a09fc12242ee
npm notice created a lockfile as package-lock.json. You should commit this file.
+ node-red-node-pi-gpiod@0.0.13
added 4 packages from 2 contributors and audited 347 packages in 12.238s

2 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-dashboard@2.23.0
added 50 packages from 47 contributors and audited 397 packages in 26.489s

2 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-contrib-influxdb@0.4.1
added 3 packages from 6 contributors and audited 400 packages in 15.369s

2 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-contrib-boolean-logic@0.0.3
added 1 package from 1 contributor and audited 401 packages in 12.278s

2 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-node-rbe@0.2.9
updated 1 package and audited 402 packages in 12.141s

2 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
+ node-red-configurable-ping@1.0.1
added 1 package from 1 contributor and audited 403 packages in 12.198s

2 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

> nodemailer@6.4.10 postinstall /usr/src/node-red/node_modules/mailparser/node_modules/nodemailer
> node -e "try{require('./postinstall')}catch(e){}"


> nodemailer@6.4.11 postinstall /usr/src/node-red/node_modules/nodemailer
> node -e "try{require('./postinstall')}catch(e){}"

+ node-red-node-email@1.7.8
added 28 packages from 15 contributors and audited 431 packages in 25.339s

2 packages are looking for funding
  run `npm fund` for details

found 4 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
Removing intermediate container a09fc12242ee
 ---> 8c9893d9dd70
Step 3/3 : RUN npm install --unsafe-perm node-red-node-sqlite
 ---> Running in e3c71a5d7fb9


 
... a huge number of compiler warnings from SQLite omitted ...
... a huge number of compiler warnings from SQLite omitted ...
... a huge number of compiler warnings from SQLite omitted ...



Successfully built 1c78512087e0
Successfully tagged iotstack_nodered:latest
WARNING: Image for service nodered was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Pulling influxdb (influxdb:latest)...
latest: Pulling from library/influxdb
05dc12a0df61: Pull complete
1b998b2d4ee2: Pull complete
15230f55c10a: Pull complete
80c79c869c88: Pull complete
50517883a6ec: Pull complete
dc1016feb388: Pull complete
e5e2c4ecbbac: Pull complete
dc4376acd754: Pull complete
Digest: sha256:0c0f5a904b151e8b322cc2b7bd1f65b334afcdf5cc6dab4113601b9c4e46e84f
Status: Downloaded newer image for influxdb:latest
Pulling grafana (grafana/grafana:)...
latest: Pulling from grafana/grafana
52278dd8e579: Pull complete
a3407674b81c: Pull complete
4f4fb700ef54: Pull complete
be318a04f8b3: Pull complete
31db28c7b77a: Pull complete
e713894ebec4: Pull complete
Digest: sha256:61c56f3d9551afecf9a10e9f8b30a5055ceafa581cdb397b56d3b6efe6632561
Status: Downloaded newer image for grafana/grafana:latest
Pulling mosquitto (eclipse-mosquitto:)...
latest: Pulling from library/eclipse-mosquitto
b4b72e716706: Pull complete
faebb82b5324: Pull complete
cc8c600a5a55: Pull complete
Digest: sha256:6ba79811d4787e10396fc5ac4784dccce235973c4351ffcd4d22f1c6ca7c44d1
Status: Downloaded newer image for eclipse-mosquitto:latest
Creating mosquitto ... done
Creating grafana   ... done
Creating nodered   ... done
Creating portainer ... done
Creating influxdb  ... done

$ docker-compose ps

  Name                 Command                  State                                       Ports                                 
----------------------------------------------------------------------------------------------------------------------------------
grafana     /run.sh                          Up             0.0.0.0:3000->3000/tcp                                                
influxdb    /entrypoint.sh influxd           Up             0.0.0.0:2003->2003/tcp, 0.0.0.0:8083->8083/tcp, 0.0.0.0:8086->8086/tcp
mosquitto   /docker-entrypoint.sh /usr ...   Up             0.0.0.0:1883->1883/tcp                                                
nodered     npm start --cache /data/.n ...   Up (healthy)   0.0.0.0:1880->1880/tcp                                                
portainer   /portainer                       Up             0.0.0.0:9000->9000/tcp                                                

$ uname -a

Linux octopi 5.4.51-v7+ #1327 SMP Thu Jul 23 10:58:46 BST 2020 armv7l GNU/Linux

$ docker -v

Docker version 19.03.12, build 48a6621

$ head -1 docker-compose.yml

version: '3.6'
```

**Comment by kentahikaru** [comment]
> On my RPi 4
> 
> ```
> $ uname -a
> Linux sec-dev 5.4.51-v7l+ #1327 SMP Thu Jul 23 11:04:39 BST 2020 armv7l GNU/Linux
> $ docker -v
> Docker version 19.03.12, build 48a6621
> $ head -1 docker-compose.yml
> version: '3.6'
> ```
> 
> Can't think why a Raspbian update would fix anything but perhaps try `sudo apt update; sudo apt upgrade`.
> 
> Also, how did you install docker? I've noticed some strange behaviours that were ultimately traced to docker being installed "by hand" using `apt` rather than via the menu. If you didn't install it via the menu, perhaps try `sudo apt remove docker docker-compose` then run the menu and let it install docker. The menu does it like this:
> 
> ```
> curl -fsSL https://get.docker.com | sh
> sudo usermod -G docker -a $USER
> sudo usermod -G bluetooth -a $USER
> sudo apt install -y docker-compose
> ```
> 
> If neither of those work, I'm at a loss to explain what you're seeing.

I tried to uninstall docker and reinstall it from menu but no luck. Still the same error.
I tried to use --verbose to maybe get more info but there is nothing useful.
Is there some way how to debug this ?

**Comment by kentahikaru** [comment]
Hm, i guess my docker-compose is old ?
pi@amalthea:~/IOTstack $ docker-compose -v
docker-compose version 1.8.0, build unknown

**Comment by kentahikaru** [comment]
pi@amalthea:~/IOTstack $ ./menu.sh 
~/IOTstack ~/IOTstack
checking for project update
From https://github.com/SensorsIot/IOTstack
 * branch            master     -> FETCH_HEAD
An update is available for the project
docker not installed
Install Docker
# Executing docker install script, commit: 26ff363bcf3b3f5a00498ac43694bf1c7d9ce16c
+ sudo -E sh -c apt-get update -qq >/dev/null
+ sudo -E sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sudo -E sh -c curl -fsSL "https://download.docker.com/linux/raspbian/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sudo -E sh -c echo "deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable" > /etc/apt/sources.list.d/docker.list
+ sudo -E sh -c apt-get update -qq >/dev/null
+ [ -n  ]
+ sudo -E sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
+ sudo -E sh -c docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a6621
 Built:             Mon Jun 22 15:53:00 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a6621
  Built:            Mon Jun 22 15:47:00 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker pi

Remember that you will have to log out and back in for this to take effect!

WARNING: Adding a user to the "docker" group will grant the ability to run
         containers which can be used to obtain root privileges on the
         docker host.
         Refer to https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
         for more information.
Install docker-compose
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  coinor-libipopt1v5 libmumps-seq-4.10.0 libraw15
Use 'sudo apt autoremove' to remove them.
Recommended packages:
  docker.io
The following NEW packages will be installed:
  docker-compose
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/121 kB of archives.
After this operation, 403 kB of additional disk space will be used.
Selecting previously unselected package docker-compose.
(Reading database ... 144109 files and directories currently installed.)
Preparing to unpack .../docker-compose_1.8.0-2_all.deb ...
Unpacking docker-compose (1.8.0-2) ...
Setting up docker-compose (1.8.0-2) ...
Processing triggers for man-db (2.7.6.1-2) ...

**Comment by kentahikaru** [comment]
Why is the raspbian installing old packages?
pi@amalthea:~/IOTstack $ sudo apt show docker-compose
Package: docker-compose
Version: 1.8.0-2
Priority: optional
Section: admin
Maintainer: Felipe Sateler <fsateler@debian.org>
Installed-Size: 403 kB
Depends: python-cached-property, python-docker (>= 1.9.0), python-dockerpty (>= 0.4.1), python-docopt, python-enum34 (>= 1.0.4), python-jsonschema, python-requests (>= 2.6.1), python-six (>= 1.3.0), python-texttable, python-websocket, python-yaml, python:any (<< 2.8), python:any (>= 2.7.5-5~)
Recommends: docker.io (>= 1.9.0)
Homepage: http://docs.docker.com/compose/
Download-Size: 121 kB
APT-Manual-Installed: yes
APT-Sources: http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages
Description: Punctual, lightweight development environments using Docker
 docker-compose is a service management software built on top of docker. Define
 your services and their relationships in a simple YAML file, and let compose
 handle the rest.

pi@amalthea:~/IOTstack $ sudo apt show docker.io
Package: docker.io
Version: 1.8.3~ds1-2
Built-Using: glibc (= 2.19-22)
Priority: optional
Section: admin
Maintainer: Paul Tagliamonte <paultag@debian.org>
Installed-Size: 22.8 MB
Depends: adduser, iptables, init-system-helpers (>= 1.18~), perl, libapparmor1 (>= 2.6~devel), libc6 (>= 2.14), libdevmapper1.02.1 (>= 2:1.02.97), libsqlite3-0 (>= 3.5.9)
Recommends: ca-certificates, cgroupfs-mount | cgroup-lite, git, xz-utils
Suggests: aufs-tools, btrfs-tools, debootstrap, lxc, rinse, zfs-fuse | zfsutils
Breaks: docker (<< 1.5~)
Replaces: docker (<< 1.5~)
Homepage: https://dockerproject.com
Download-Size: 4,835 kB
APT-Sources: http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages

**Comment by Paraphraser** [comment]
Well, for the record, on the RPi3B+ I used yesterday:

```
pi@octopi:~$ cat /proc/device-tree/model; echo ""
Raspberry Pi 3 Model B Plus Rev 1.3

pi@octopi:~$ docker -v
Docker version 19.03.12, build 48a6621

pi@octopi:~$ docker-compose -v
docker-compose version 1.21.0, build unknown

pi@octopi:~$ apt show docker.io 2>/dev/null | head -2 2>/dev/null
Package: docker.io
Version: 18.09.1+dfsg1-7.1+rpi1+rpt1
```

I don't know enough about `apt` to make sensible comments but, from stuff I have seen elsewhere, I gather that there are some "seed" lists somewhere inside the guts of Raspbian which are used by `apt update` to fetch the information that is used to decide what `apt upgrade` should do. The whole system breaks down if those seed lists are out-of-date but how one goes about fixing that problem is something I don't know. Once I strike a problem like that, I make the assumption that it is unlikely that only one thing is broken, so it's time to start with a clean installation of the most-recent image on a brand new SD card.

If you're running a clean install of IOTstack but are getting obsolete versions then it seems to me that the above scenario is a plausible explanation, provided that you did **not** start from a clean install of Raspbian.

If you **did** start from a clean install of 2020-05-27 Raspbian then I have absolutely no idea what might be going on. Sorry.

**Comment by kentahikaru** [comment]
I put fresh raspberry pi os on my SD card and it's working.
docker-composer is 1.21 and it's downloading docker images.

Thank you all !

**Comment by Paraphraser** [comment]
Excellent!
