### ISSUE TITLE
Running on an Ubuntu Server

### ISSUE THREAD

**Issue by ceinem** [SensorsIot/IOTstack#111]
I'm a big fan of this stack, great work! 
I preferred running this on an Ubuntu server rather than a Raspberry Pi and thought I would share some of the changes I had to make. Maybe this is something for the documentation? The chapter on running on a Virtual Machine in the wiki is not the most extensive 😄 

I had an issue with docker versions, manually changing the docker-compose file to version 3.3 fixed this. Not sure what the issue here is. 

for some containers, the specification in the docker-compose file is not suitable for ubuntu. For example I had to change the homebridge entry to: oznu/homebridge:latest

There were also some issues with starting the stack, this was also reported on [the original repo](https://github.com/gcgarner/IOTstack/issues/29)

run:
```
export DOCKER_HOST=127.0.0.1:2375
sudo service docker start
sudo docker-compose up -d
```

after rebooting, run:
```
sudo service docker start
sudo docker-compose up -d
```

**Comment by ukkopahis** [comment]
Thanks for the info.
As IOTstack officially supports only Raspberry Pi, virtual machine setups are outside the scope of the project.
