### ISSUE TITLE
docker not installed

### ISSUE THREAD

**Issue by Tasm-Devil** [SensorsIot/IOTstack#146]
Hi,
I'm new to this project and wanted to play around with it in a fresh installation of ubuntu-minimal.
After cloning the repo and calling ./menu.sh, I get the following

```
~/IOTstack$ ./menu.sh 
~/IOTstack ~/IOTstack
checking for project update
From https://github.com/SensorsIot/IOTstack
 * branch            master     -> FETCH_HEAD
Project is up to date
docker not installed
~/IOTstack$
```

Why is that so? I read [here](https://sensorsiot.github.io/IOTstack/Getting-Started/#menu-item-install-docker) that I shouldn't install docker via apt.

**Comment by Tasm-Devil** [comment]
OK. Here is the reason: whiptail is not installed
`sudo apt install whiptail`
solves it.

**Comment by Slyke** [comment]
Hmm, you may experience further issues. I haven't tested out the stack on minimal Ubuntu. I always use the standard server distro.

**Comment by Tasm-Devil** [comment]
For the moment, it works like a charm. I use node-red, mosquito, influxdb, grafana and portainer. Just fine.
