### ISSUE TITLE
 docker-compose up fails -- response to new repo

### ISSUE THREAD

**Issue by okriso** [SensorsIot/IOTstack#156]
@Slyke Firstly, thanks for responding and apologies for not posting my original issue in the correct location. 

I changed my routers DNS settings to ensure the PiHole DNS was not active. 

You asked me to execute the following commands:
`
sudo apt update
sudo apt install dnsutils
dig registry-1.docker.io
`
This was the output is further down, after i ran the commands i ran the 'up' command and it appears that its all working now. I'm almost certain it was my adjusting the ports for my custom container to stop conflict with openhab. 

`
; <<>> DiG 9.11.5-P4-5.1+deb10u2-Raspbian <<>> registry-1.docker.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 9904
;; flags: qr rd ra; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;registry-1.docker.io.		IN	A

;; ANSWER SECTION:
registry-1.docker.io.	60	IN	A	52.5.11.128
registry-1.docker.io.	60	IN	A	3.211.199.249
registry-1.docker.io.	60	IN	A	18.213.137.78
registry-1.docker.io.	60	IN	A	54.236.131.166
registry-1.docker.io.	60	IN	A	54.85.56.253
registry-1.docker.io.	60	IN	A	52.54.232.21
registry-1.docker.io.	60	IN	A	107.23.149.57
registry-1.docker.io.	60	IN	A	34.195.246.183

;; Query time: 19 msec
;; SERVER: 192.168.88.1#53(192.168.88.1)
;; WHEN: Wed Oct 21 19:22:36 AEDT 2020
;; MSG SIZE  rcvd: 166
`
Thanks again, i will have a look through the issues in this repo for answers from now on.

**Comment by Slyke** [comment]
For reference, this is the thread from the old repo: https://github.com/gcgarner/IOTstack/issues/210
