### ISSUE TITLE
Portainer menu.sh

### ISSUE THREAD

**Issue by Schnuecks** [SensorsIot/IOTstack#169]
Hi, if i select portainer-ce and build the stack, on the next run of menu.sh portainer and portainer-ce are selected.
On every run i must deselect portainer. selection.txt only contains portainer-ce

**Comment by CharlesGodwin** [comment]
This is a bug. In `menu.sh` at line 457 there is this test
`[ $(grep "$index" ./services/selection.txt) ] && entry_options+=("ON") || entry_options+=("OFF")`

It finds portainer twice, once for portainer-ce and once for portainer

The solution  is to change it to search for a match of the entire line  in selections.txt
`[ $(grep --line-regexp "$index" ./services/selection.txt) ] && entry_options+=("ON") || entry_options+=("OFF")`

I doubt if I'm skilled enough to build a pull request for this but I may give it a try in a few days, once I finish another project.

**Comment by Schnuecks** [comment]
Great, thanks for looking at the code.

**Comment by DevSaumyadip** [comment]
on stack building update , add portainer 2.0 with docker pull portainer/portainer-ce:latest
