### ISSUE TITLE
Python Install Fails

### ISSUE THREAD

**Issue by eleff210** [SensorsIot/IOTstack#170]
I saw this posted on the prior fork but not seeing the same here.  I'm having an issue where when running docker-compose up -d I get an error attributed to the installation/update of Python.  I've traced it back to no "requirements.txt" file being found in the dynamically created tmp path.  Any ideas on how to fix or what might be within the requirements.txt file so that I can create it?

![image](https://user-images.githubusercontent.com/11710974/98135713-c5073680-1e85-11eb-8588-4f823ddc042a.png)

**Comment by StohanzlMart** [comment]
You need to specify your imports here!

https://www.docker.com/blog/containerized-python-development-part-1/

Example requirements.txt (from a Python project I'm trying to containerise rn): https://github.com/ThomDietrich/miflora-mqtt-daemon/blob/master/requirements.txt

**Comment by StohanzlMart** [comment]
Apparantly you can "pip freeze > requirements.txt"

source: https://www.youtube.com/watch?v=gHaFqYRJ_aw
