### ISSUE TITLE
docker_backup script not uploading to defined dropbox folder

### ISSUE THREAD

**Issue by al7arthi** [SensorsIot/IOTstack#171]
In line 66 of the docker_backup script, the dropboxfolder variable is not used to define the destination folder, the backupfile is used twice instead. This causes the backup files to be uploaded to dropbox root directory.
https://github.com/SensorsIot/IOTstack/blob/9f44324179d29307dea52c0df52918afedc5ca2c/scripts/docker_backup.sh#L66

**Comment by 877dev** [comment]
@al7arthi this should be fixed now: https://github.com/SensorsIot/IOTstack/pull/195
