### ISSUE TITLE
Running Python script command line from cron job

### ISSUE THREAD

**Issue by ronnyandre** [SensorsIot/IOTstack#173]
I have a Python script that will fetch data from external source two times a day. I thought I would solve this by having a cron job invoking the Python script inside the Docker container.

Is it really as straight forward as creating the script in a container and then do a cron job that will exec this script?

Just asking because to me it seems like the Python container will continously run as a server?

**Comment by ukkopahis** [comment]
Yes, Python container is for a continuously running application.

For a cron job container I'd start from https://github.com/linuxserver/docker-duckdns/ and customize the Dockerfile to install python (RUN apk add python)

Is this straightforward? Yes. If this is your first custom container, then maybe not so much.
