### ISSUE TITLE
Experimental branch - odd transient behaviour on RPi3B+

### ISSUE THREAD

**Issue by Paraphraser** [SensorsIot/IOTstack#174]
### Summary

I noticed some oddities while testing the "experimental" branch on a RPi3B+:

* an unexpected prompt for a second `git pull` after switching to "experimental"
* an unexpected prompt to re-add "pi" to the bluetooth group (the old menu should already have done that)
* an unexpected freeze during reboot
* impossible up-time messages from Docker.

Each problem has gone away so they appear to be one-offs. I am only opening this issue to document what I saw in case other people strike similar issues and are able to capture more evidence.

### Detail

RPi3B+. Last rebuilt 2020-10-24 to test bare-metal restore:

* Raspbian
* Clone IOTstack
* Run (old) menu to install Docker
* Restore IOTstack content from backup.
* Stack up.
* Finito.

Today:

* Checkout experimental branch:

	```
	$ cd ~/IOTstack
	$ git pull
	$ git checkout experimental
	```
	
	Git then wanted another pull <sup>([Second pull?](#SecondPull))</sup>:
	
	```
	$ git pull
	```

* Run new menu. Updates python. Grizzles "not a member of bluetooth" <sup>([Bluetooth group re-add?](#BluetoothGroupReAdd))</sup>

* As prompted:

	- ran `./menu.sh --run-env-setup`
	- rebooted.

All my RPis run headless. Whenever I reboot, I generally set up a ping from a 2nd host, emitting ICMP Echo Requests at the default rate of 1 per second, so I know when the rebooting RPi comes back.

Once the reboot is triggered, the expected ping pattern is:

* 15 replies (mainly while containers stop)
* 30 no replies (while the machine actually reboots)
* continuous replies.

Today, the observed behaviour of the RPi3B+ was:

* 15 replies
* 30 no replies
* 3 replies
* no replies

Frozen. I waited 5 minutes then power-cycled. It came back OK 30 seconds later. But, ssh followed by a (short form of) `docker ps` showed:

```
Linux octopi 5.4.72-v7+ #1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l
...
Last login: Sun Nov  8 09:26:44 2020 from 192.168.132.199

$ DPS
NAMES               CREATED             STATUS
nodered             13 minutes ago      Up 6 minutes (health: starting)
pihole              13 minutes ago      Up 6 minutes (health: starting)
mosquitto           13 minutes ago      Up 6 minutes
influxdb            13 minutes ago      Up 6 minutes
portainer-ce        13 minutes ago      Up 6 minutes
gitea               13 minutes ago      Up 6 minutes
grafana             13 minutes ago      Up 6 minutes
```

"Up 6 minutes". Bovine dung! Reboot again. Follows expected ping pattern, then:

```
NAMES               CREATED             STATUS
nodered             30 minutes ago      Up About a minute (healthy)
pihole              30 minutes ago      Up About a minute (healthy)
mosquitto           30 minutes ago      Up About a minute
influxdb            30 minutes ago      Up About a minute
portainer-ce        30 minutes ago      Up About a minute
gitea               30 minutes ago      Up About a minute
grafana             30 minutes ago      Up About a minute
```

This time "status" is sensible.

Then I checked whether "pi" was a member of "bluetooth":

```
$ groups
pi adm dialout cdrom sudo audio video plugdev games users input netdev bluetooth docker gpio i2c spi
```

It is. I re-ran the (new) menu. There was no recurrence of the complaint about the bluetooth group. 

<hr>

### <a name="SecondPull">Second pull?</a>

I don't recall ever needing a second pull before.
 
On my "test" RPi4 (where "experimental" has been checked-out before), I did:

```
$ cd ~/IOTstack
$ git pull
$ git checkout experimental
```

There was no prompt for a second pull. The logical inference is that this is either:

* some peculiarity of the RPI3B+; and/or
* some side-effect of the unexpected bluetooth group complaint; and/or
* the fact that I've never previously done a checkout of "experimental" on the RPI3B+.

### <a name="BluetoothGroupReAdd">Bluetooth group re-add?</a>

The bluetooth grizzle was unexpected because the old menu had been run (to install Docker). The old menu also checks and repairs bluetooth group membership. There really is no way that "pi" could not have been a member of "bluetooth" but I can't go back in time to run "groups" and see.

While the RPi4 was in "experimental" I ran the (new) menu. It wanted to update Python but did not moan about non-membership of bluetooth so, again, this seems to be a RPi3B+ peculiarity.

**Comment by Slyke** [comment]
It's possible that I was doing some pushing while you were also updating. Have these issues still been occurring?
