### ISSUE TITLE
Portainer Container List > homeassistant is stopped

### ISSUE THREAD

**Issue by toreupfeet** [SensorsIot/IOTstack#177]
I've installed from scratch a few times with this same result every time: 

Upon installation of Docker, building and installing Stack, and then installing Hassio (Rpi4 64 8gb) the 8123 port does not resolve. I login to Portainer and after a few refreshes the Container List shows homeassistant as "stopped". I click into the details and the status reads that it is "stopped ... with exit code 1". All other containers are running just fine (hassio_audio, hassio_supervisor, etc.) and the observer resolves at 4357:80.

Image: homeassistant/raspberrypi4-64-homeassistant:0.117.5

edit: I should note that I am brand new to pi. If anyone can point me toward a simple (and easy to follow) fix, I'd be very interested, and grateful.

edit again: I read on the HA community site that someone else was having a similar problem with 117.5, specifically when using the ethernet port. I shut down and unplugged, restarted without an ethernet cable (so I could use the wlan0), and now the wifi adapter won't activate. "dhcpcd not running". I had this issue at least once yesterday as well. I'm new, so every time I experience an issue like this I just start over from a fresh Raspberry Pi 32-bit OS image and proceed from there. I've done so enough times that I can say with confidence that I'm following the steps correctly. And so here I am, reaching out. To clarify, the wlan0 works fine when I install a fresh Raspberry OS. I don't know at what point of the installations the dhcpcd stops running.

**Comment by saket424** [comment]
@toreupfeet 
Downgrading to docker 19.03.14 fixed it for me as suggested here

https://github.com/SensorsIot/IOTstack/issues/196
