### ISSUE TITLE
Adding service to compose-override.yml doesn't merge into docker-compose.yml

### ISSUE THREAD

**Issue by ronnyandre** [SensorsIot/IOTstack#202]
I added a new service to the `compose-override.yml` file, however thes are not taken into consideration when running `docker-compose up -d`

I have previously added custom containers earlier, and they are running as normal.

Not sure how to invoke the `yaml_merge.py` script to force update the docker yaml.

**Comment by Schnuecks** [comment]
Just run menu.sh and build the stack again and all changes in compose-override.yml will be merged into docker-compose.yml.

**Comment by ronnyandre** [comment]
I feel stupid now, but this works of course.. Thanks!
