### ISSUE TITLE
docker is not being added to groups ??

### ISSUE THREAD

**Issue by ithinkido** [SensorsIot/IOTstack#204]
After a fresh install of Raspbian as well as IOTstack I was greeted with this error
`Error getting docker version. Received permission denied error`
On a guess I added docker to groups with
`sudo usermod -aG docker $USER`
This seems to have solved the issue

**Comment by Slyke** [comment]
This is related to https://github.com/SensorsIot/IOTstack/issues/205 investigating.

**Comment by Slyke** [comment]
Hey @ithinkido did this error occur after restarting?

**Comment by ithinkido** [comment]
Yes, and i can confirm that docker was not being added to groups.

**Comment by Slyke** [comment]
I have a potential fix for this on the `experimental` branch. I want to test it out on a fresh RPi before merging to master in case it breaks anything.

**Comment by chris2286266** [comment]
> After a fresh install of Raspbian as well as IOTstack I was greeted with this error
> `Error getting docker version. Received permission denied error`
> On a guess I added docker to groups with
> `sudo usermod -aG docker $USER`

Actually the mentioned command does not add docker to groups, it adds the current user (e.g. pi) to group docker, which solves the issue.

**Comment by ithinkido** [comment]
> 
> 
> > After a fresh install of Raspbian as well as IOTstack I was greeted with this error
> > `Error getting docker version. Received permission denied error`
> > On a guess I added docker to groups with
> > `sudo usermod -aG docker $USER`
> 
> Actually the mentioned command does not add docker to groups, it adds the current user (e.g. pi) to group docker, which solves the issue.

OK

**Comment by ukkopahis** [comment]
I'll assume the long inactivity indicates menu.sh now solves this.
