### ISSUE TITLE
Selecting last item in Build Stack menu exits instead

### ISSUE THREAD

**Issue by dhennessy** [SensorsIot/IOTstack#208]
To reproduce:

Choose Build Stack
Press up (navigate to zigbee2mqtt_assistant)
Press space (to select)

Effect:
The script exits.

**Comment by Slyke** [comment]
Have confirmed this issue. There's an error in the service.yml file:
![image](https://user-images.githubusercontent.com/6442613/102865460-a2f05600-43ea-11eb-8666-c77eb6f82753.png)

I have fixed this in the latest push to master. If you have further problems, feel free to reopen the issue.
