### ISSUE TITLE
MozillaIOT is now Webthings, please fix in yaml file, idk how to git gud :D yet

### ISSUE THREAD

**Issue by StohanzlMart** [SensorsIot/IOTstack#209]
https://github.com/WebThingsIO/gateway/releases

changed Mozillaiot to webthingsIO, see

https://hub.docker.com/r/webthingsio/gateway

a simple fix for the menu.sh 🤣

**Comment by Slyke** [comment]
I have pushed a fix that updates the template file. Please reopen if there's more issues with this service that IOTstack can fix.
