### ISSUE TITLE
Home Assistant navtive(supervised) stack integration static IP

### ISSUE THREAD

**Issue by breemts** [SensorsIot/IOTstack#225]
My setup is home assistant native(supervised) and some nodes like deconz, nodered and mosquitto. 
When restarting the docker services it is not guaranteed that every service gets the same IP as last time. E.g. deconz with IP 192.16.238.5 is not guaranteed to get this IP the next boot.

With home assistant setup as part of the stack it is possible to access the other services by name, because alle are in the iotstack_nw network. Correct me if I'm wrong but with the native home assistant setup this isn't possible, right?

A Workaround for me was to override the `docker-compose.yml` and define a static ip for the services that I want to connect to Hass.io.
```
    networks:
      iotstack_nw:
        ipv4_address: 192.16.238.100
```
Unfortunately this doesn't work when I write this in the `compose-override.yml` file. So this is not very reliably. 
Also for deconz I tried to integrate it in hass.io manually with 127.0.0.1 but it's aborting with "already configured", which is not true.

Does anyone have an idea how to solve this?

**Comment by ukkopahis** [comment]
Native/supervised Home Assistant is no longer supported, marking issue to be closed.
