### ISSUE TITLE
Can i use this on a VM

### ISSUE THREAD

**Issue by Bibi40k** [SensorsIot/IOTstack#227]
Hi, can i install IOTstack on a linux in a VM ?
I don't want to buy a new hardware as long as i have FreeNAS server running 24/7 ?

Of course i can install all the packagess manually but it would be nice to use your scripts.

Thanks

**Comment by lucibuz** [comment]
Yes you can, I have the IOTstack running  on a ubuntu server 20.04.
To install it I use the following:

git clone https://github.com/SensorsIot/IOTstack.git IOTstack

cd ~/IOTstack
./menu.sh
