### ISSUE TITLE
Warning when running docker-compose up -d

### ISSUE THREAD

**Issue by mike-blackwell-0o0** [SensorsIot/IOTstack#230]
After initial install, I selected several containers to build, and then docker-compose up -d to start the stack.  I receive a warning some networks were defined but are not used by any service: iotstack_nw_internal, nextcloud_internal, vpn_nw, itostack_nw.   The stack started and the process immediately terminated.  It does not appear that any of the containers ran.

**Comment by memjr** [comment]
You can ignore that warning.
