### ISSUE TITLE
telegraf  telegraf.conf  is missing 

### ISSUE THREAD

**Issue by reba0** [SensorsIot/IOTstack#234]
@ installation:  the  telegraf.conf is not pulled from ../IOTstack/.templates/telegraf to 
.../IOTstack/services/telegraf  and installation fails

**Comment by Paraphraser** [comment]
It doesn't look like anyone has answered your question. Sorry about that.

See [Issue 256](https://github.com/SensorsIot/IOTstack/issues/256#issuecomment-766426963).

**Comment by ukkopahis** [comment]
This issue seems to be resolved.

**Comment by Paraphraser** [comment]
Concur - starting with #394
