### ISSUE TITLE
Mosquitto :  failed  to save /mosquitto/data/mosquitto.db.new for writing

### ISSUE THREAD

**Issue by reba0** [SensorsIot/IOTstack#237]
Wrong  user  in  Volumes directory   :    default User instead of  "1883"

LOG Output 
today at 01:41  2021-01-12T22:11:01: Error saving in-memory database, unable to open /mosquitto/data/mosquitto.db.new for writing.
today at 01:41  2021-01-12T22:11:01: Error: Invalid argument.

pi@raspi-test:~/IOTstack/volumes $ ls -al
insgesamt 24
drwxr-xr-x  5 pi   pi   4096 Jan 12 16:17 mosquitto
.templates is a directoryfix.sh   
copied  directoryfix.sh to  /IOTSTACK/
copied   service.yml   to   IOTSTACK/Services/mosquitto 

executeted the  direcotory fix 

pi@raspi-test:~/IOTstack/volumes $ ls -al
drwxr-xr-x  5 1883 1883 4096 Jan 12 16:17 mosquitto

working

**Comment by senarvi** [comment]
I had the same problem and had to do the same fix.

**Comment by azakow** [comment]
same issue here; I understand to fix the issue I need to run directoryfix.sh; where can I get this file; sry I am completely new to such things here in github

**Comment by azakow** [comment]
🤦 found it; sry

**Comment by batamire** [comment]
For anyone stumbling, manual command is: `sudo chown -R 1883:1883 /home/pi/IOTstack/volumes/mosquitto`

**Comment by ukkopahis** [comment]
Problem now should be prevented by #350.
