### ISSUE TITLE
Unchecking Service in "Build Stack" does not remove it from docker-compose.yml

### ISSUE THREAD

**Issue by rysk-de** [SensorsIot/IOTstack#272]
Hi,

im giving IOTstack a try an did run in a little issue:
Unchecking a Service in "Build Stack" does nothing to the docker-compose.yml. It says that the build is completed, but the entry in the yml-File - Plex in this instance - is not removed and therefore Plex is deployed again.
Removing the entry from the docker-compose.yml manually is not helping either, the box is still checked in the "Build Stack" Menu and therefore adds Plex again.

I'm running the current IOTstack version on an Ubuntu Server 20.04 inside a VirtualBox VM. Any ideas?

**Comment by obergerdavid** [comment]
Hi,
I also had this kind of issue before. The menu parses the services/docker-compose.save.yml file - in there the selected services are saved.
Please remove the service from the services/docker-compose.save.yml file and then select "Build Stack". Afterwards your docker-compose.yml should not contain the Plex service anymore.

**Comment by rysk-de** [comment]
@obergerdavid Great! That did the trick, thanks.

However, this strikes me not as a feature but as a bug or something that should be documented (I hope I didn't missed it in the documentation).
