### ISSUE TITLE
Adminer not responding

### ISSUE THREAD

**Issue by coolbikerdad** [SensorsIot/IOTstack#292]
I am successfully running IOTstack with PiHole, MariaDB, Portainer-CE, Heimdall and more. All work with the exception of Adminer, which I thought I had working a while ago, but even after a stack rebuild, deletion and recreation of container and image, does not respond on 9080:8080. Any ideas welcome.

**Comment by coolbikerdad** [comment]
I think the latest version of Adminer exceeds the default memory allocated to PHP in the container. The default is 256M, but if I set the environment variable MEMORY=512M in Portainer and redeploy the container, Adminer works again.

**Comment by MennoSchakel** [comment]
For me setting the environment variable MEMORY=512M still doesn't have Adminer responding. Downgrading from Adminer:latests (i.e. 4.8.0) to 4.7.8 (the version running on my live version), does not change anything.
On my current live IOTstack (running old menu) Adminer is running without issues.

**Comment by wiliezwagerman** [comment]
I had the same issue on a Raspberry Pi 4, it seems to be an issue for adminer images 4.7.8+
Reverting to 4.7.7 solved the issue for me.
[https://github.com/TimWolla/docker-adminer/issues/96](url)
