### ISSUE TITLE
Portainer and Portainer-CE ports on master branch at variance with documentation

### ISSUE THREAD

**Issue by Paraphraser** [SensorsIot/IOTstack#299]
@Slyke - hate to add to your load but...

In a [Discord post](https://discord.com/channels/638610460567928832/638610461109256194/826117467038023714) @SensorsIot said he ran into a problem with conflicting Portainer ports.

Andreas is correct. Master branch and old-menu are exact inverses:

* master branch:
	* Portainer uses port 9002
	* Portainer-CE uses port 9000
* old-menu branch:
	* Portainer uses port 9000
	* Portainer-CE uses port 9002

This is a situation where I simply don't understand how or why it came to be. The relevant commit seems to be:

```
commit 75f0b5762065512742a8860f1a2665d15085c9f0
Author: Slyke
Date:   Thu Oct 15 21:02:25 2020 -0700

    Updated portainer ports
```

> Given the timestamp, I'm slightly surprised that nobody else has raised this before.

It's at variance with the [Portainer-CE documentation](https://github.com/SensorsIot/IOTstack/blob/master/docs/Containers/Portainer-ce.md#port-number--9002) and the [original rationale](https://github.com/SensorsIot/IOTstack/pull/136).

My 2¢ is that the port allocation on the master branch should reflect the documentation and the original rationale.

It also seems to me that it's a bad precedent to allow a *later* container to pre-empt a prior claim on a port. I think that's a very short path to chaos.

Thoughts?

Any other changes like this lurking in the woodwork?

**Comment by wijnsema** [comment]
All the more reason to get rid of the portainer container like I proposed in #289.
You have to get rid of old stuff once in a while to keep things tidy.

**Comment by Paraphraser** [comment]
Well, I tend to agree (with the idea that pruning and maintenance will be needed from time to time). The problem, as I see it, is that we have no way of being **sure** that nobody is using vanilla Portainer. After all, people keep popping up out of the woodwork on the gcgarner repo (latest one only six days ago). Unless they've gone to the trouble of updating to CE by hand, they'll be on vanilla Portainer. When they migrate the ground will shift under them. I agree it's no big deal in the scheme of things but I also think it does no great harm to let it coexist for a while longer. My 2c.
