### ISSUE TITLE
error on docker python

### ISSUE THREAD

**Issue by penrose72** [SensorsIot/IOTstack#316]
I have try several time. With installation from scratch for avoid "noise".

But always have this error:

Step 3/5 : COPY requirements.txt ./
ERROR: Service 'python' failed to build: COPY failed: file not found in build context or excluded by .dockerignore: stat requirements.txt: file does not exist

**Comment by dinpoplaca** [comment]
same here. I had to delete the Python config from Docker-compose to work. when I add that back it breaks again.
same thing happened with node red and I removed node red too. I cannot add them back via the menu. as soon as I select them it breaks the docker-Compose file.

**Comment by hi3ronym0s** [comment]
I have the exact same problem.

**Comment by ukkopahis** [comment]
For the python service to work, you need follow:
https://sensorsiot.github.io/IOTstack/Containers/Python/#addingPackages

**Comment by ukkopahis** [comment]
The Python service is for developing your own application.
For the python service to work, you need follow:
https://sensorsiot.github.io/IOTstack/Containers/Python/#addingPackages
