### ISSUE TITLE
Cannot install nodered.

### ISSUE THREAD

**Issue by dinpoplaca** [SensorsIot/IOTstack#321]
This happens on anything i tried to run this script on.  Raspbery Pi 3 and an Ubuntu machine.

pi@raspberry:~/IOTstack$ docker-compose up -d
WARNING: Some networks were defined but are not used by any service: nextcloud_internal, iotstack_nw_internal
Building nodered
**ERROR: Cannot locate specified Dockerfile: Dockerfile**

and the config in the docker-compose .yml is:
nodered:
    container_name: nodered
    build: ./services/nodered/.
    restart: unless-stopped
    user: "0"
    privileged: true
    environment:
    - TZ=Etc/UTC
    ports:
    - "1880:1880"
    volumes:
    - ./volumes/nodered/data:/data
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    devices:
    - "/dev/ttyAMA0:/dev/ttyAMA0"
    - "/dev/vcio:/dev/vcio"
    - "/dev/gpiomem:/dev/gpiomem"
    networks:
    - iotstack_nw

**Comment by Paraphraser** [comment]
Did you sort this out? The most common reason for this is (a) choosing NodeRed in the menu but (b) **not** using the right arrow to go into the sub-menu to select at least one add-on node.

Selecting add-on nodes is what generates the Dockerfile.

Under old menu (old-menu branch) this step was forced. Under new menu (master branch) it's required but not forced and it's fairly easy to miss. Under new-new menu (experimental branch), Slyke says it will be forced again.
