### ISSUE TITLE
Docker permission denied after installed by IOTstack menu

### ISSUE THREAD

**Issue by steanrdr** [SensorsIot/IOTstack#363]
A fresh Raspberry Pi. 1. Installed Raspberry OS, 2. apt update, 3. apt full-upgrade. 4. Reboot.  5. clone IOTstack 6. Run the menu.
As menu asked, if to install docker, typed yes. After install and rebbot menu says: "access denied" at checking the docker version.

The group docker does exist. Added user pi to group and rebbot, works now.

**Comment by steanrdr** [comment]
Cloes issue. Works now.

**Comment by steanrdr** [comment]
Works now. maybe reboot or really the adding of the user pi solved it.

**Comment by Paraphraser** [comment]
I suspect there may be some paths through which all the "right things" are somehow not done or not done in the right order. Certainly, a reboot is needed for any `usermod` to take effect.

You might find [this gist](https://gist.github.com/Paraphraser/d119ae81f9e60a94e1209986d8c9e42f] helpful. Personally, I side-step all the uncertainty by building as per [this repo](https://github.com/Paraphraser/PiBuilder).
