### ISSUE TITLE
Best practice - mapping windows SMB share

### ISSUE THREAD

**Issue by tal2420** [SensorsIot/IOTstack#371]
Hi,
I couldn't find a good way to map a windows SMB share in a way that's natively supported by IOTstack.
Any advice?

**Comment by Paraphraser** [comment]
Try:

* [share from Pi](https://magpi.raspberrypi.org/articles/samba-file-server)
* [another share from Pi](https://sbcguides.com/configure-a-raspberry-pi-samba-share/)
* [mount share on Pi](https://www.looklinux.com/how-to-mount-samba-share-smbfs-in-linux/)

I wasn't sure which way you wanted to go but you should find a truth somewhere in all that.

I haven't tried any of this. I've been using sshfs and mounting the Pi folders on my Mac. That lets me do what I want so I haven't gone any further.
