### ISSUE TITLE
TLS support for defined services

### ISSUE THREAD

**Issue by marcelstoer** [SensorsIot/IOTstack#410]
I was wondering...would IOTstack somehow be able to facilitate TLS connections to defined services?

Two examples:
- (The) Home Assistant (dashboard) has limited functionality if not accessed over HTTPS
- ESPHome dashboard - I run it as a custom service - can't support flashing binaries to nodes in the browser if not accessed over HTTPS\*

Wouldn't it be cool if I could tell IOTstack to do TLS termination even if that would mean using self-signed certificates? Spin up a reverse proxy that does the necessary forwarding/mapping?

\* it uses the browser Serial API which browsers only allow for HTTPS sites

**Comment by Noschvie** [comment]
#160

**Comment by ukkopahis** [comment]
Home assistant documentation now includes how to setup SWAG: https://sensorsiot.github.io/IOTstack/Containers/Home-Assistant/#httpsWithSSLcert

Should be adoptable to also work for ESPHome.
