### ISSUE TITLE
Nextcloud calendar ingetration with iOS

### ISSUE THREAD

**Issue by Nurgak** [SensorsIot/IOTstack#434]
I am attempting setting up the Nextcloud calendar with iOS, but I found out that [starting with iOS 12 an SSL connection is required](https://docs.nextcloud.com/server/19/user_manual/pim/sync_ios.html) and the calendar will not successfully be verified without it.

I can confirm it as when I previously installed Nextcloud natively and created a certificate with [Let's Encrypt](https://letsencrypt.org/) I was successful. Now that encryption is technically not needed, as I never expose anything outside besides Wireguard port, the calendar feature does not work in iOS (says it cannot be verified). Although, I can see the calendar when I log in the Nextcloud website on the phone (over an "unsecured" connection).

My question is: how hard is it to set up some kind of certificate on the Nextcloud docker? I would like to connect to the Nextcloud instance using the IP of the RPi, such as `https://192.168.5.23:443`. Some dummy self-signed certificate would do the trick hopefully. Perhaps Traefik would be suited for this? I don't know much about it though...

**Comment by ukkopahis** [comment]
I don't think you can get a certificate for an IP-address from Let's Encrypt. You'll have to use a DNS name (e.g. mydomain.duckdns.org). The actual IP-address of the domain name can still be your LAN IP accessible only through VPN.

Home assistant documentation now includes how to setup SWAG: https://sensorsiot.github.io/IOTstack/Containers/Home-Assistant/#httpsWithSSLcert This should be adoptable to also work for you. But #160 would be easier if added.
