### ISSUE TITLE
Feature request: please include Folding@Home container in the stack

### ISSUE THREAD

**Issue by ppdesai434** [SensorsIot/IOTstack#46]
Can you please add Folding@Home to the stack for contributing towards the global pandemic?

https://hub.docker.com/r/linuxserver/foldingathome

**Comment by Slyke** [comment]
Will check it out shortly. Not sure if they support ARM, they have conflicting info:
![image](https://user-images.githubusercontent.com/6442613/81462217-c4574700-9165-11ea-8478-a9a08e3a7d6c.png)

**Comment by Willem-Dekker** [comment]
The only supported OS/ARCH is linux/amd64
