### ISSUE TITLE
 error while loading shared libraries

### ISSUE THREAD

**Issue by huseyinkogo** [SensorsIot/IOTstack#474]
Getting this error fresh install of Raspberry Pi 4
```
git clone https://github.com/SensorsIot/IOTstack.git IOTstack
Cloning into 'IOTstack'...
/usr/lib/git-core/git-remote-https: error while loading shared libraries: libhogweed.so.4: cannot open shared object file: No such file or directory
```
Tried reinstalling git curl
Tried rebooting

**Comment by Paraphraser** [comment]
Not a lot to go on...

Just did an apt update/upgrade. Nothing in it about git. Then tried a clean clone which worked so, whatever is causing your problem isn't affecting me.

![25A05075-61B0-44DC-BC0E-95A7D11EE482](https://user-images.githubusercontent.com/34226495/149284359-9425cbc7-00d9-4b61-bfd5-9187590d9d93.jpeg)

Have you tried pinging GitHub to see if it is reachable?

A lot of recent IOTstack problems turn out to be a combo of Buster and libseccomp2. Can't really see why that would affect git but if you're running Buster maybe see [recommended system patch](https://sensorsiot.github.io/IOTstack/Getting-Started/#patch-2-update-libseccomp2).

Alternatively, try rebuilding with [PiBuilder](https://github.com/Paraphraser/PiBuilder).

**Comment by huseyinkogo** [comment]
@Paraphraser thanks for the reply. Yeah i will need to re install a clean copy. maybe try the Pibuilder  :)
