### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by the1gofer** [SensorsIot/IOTstack#497]
Portainer link on https://sensorsiot.github.io/IOTstack/Home/ is broken

**Comment by ukkopahis** [comment]
That whole page is outdated.
Fixed in PR #466

Prior to that being merged, you may want to look my updated doc at:
https://ukkopahis.github.io/IOTstack/

**Comment by the1gofer** [comment]
Maybe consider removing the wiki link to that page then?

**Comment by ukkopahis** [comment]
It is indeed removed in the pull-request:
https://github.com/SensorsIot/IOTstack/pull/466/files#diff-e9e59dcd73f0a9494c18bab6e6270dcf3c67236fe11faaf4a46222fb1db0cbf4
