### ISSUE TITLE
IOTstack documentation - navigational "issue" on smaller screens

### ISSUE THREAD

**Issue by Paraphraser** [SensorsIot/IOTstack#520]
I have noticed a behavioural difference in the IOTstack Wiki which appears to depend on screen width. In some sense, this difference has always been there but the recent changes to the documentation layout have had some side-effects that might not, perhaps, have been intended.

Whether this qualifies as a true "issue" will depend on your perspective. It may also be something we will just have to live with but I thought I'd describe the problem in case there is a way to improve navigation on smaller screens.

Reference images:

![doco](https://user-images.githubusercontent.com/34226495/159404275-4379ecd6-114c-489b-81ae-91096b4d5abd.jpeg)

To me, the most natural link than anyone new to IOTstack is likely to click on is "Getting Started" (A) rather than "IOTstack Wiki" (F).

If you click (A) on a wider screen then you see the layout in (B). The major categories are listed in the horizontal strip, it is clear that "Basic setup" is currently selected, and the left hand headings will change if you click on any other category. Clear, simple, elegant, easily-navigable, well-designed UI.

On a narrower screen (eg iDevice), your journey is a bit different. At (C) there is no horizontal strip and the user just has to know to click on the "≡" icon to reveal the slide-out panel (D). That's a fairly standard icon and a common UI paradigm so it's probably a reasonable assumption that the user will click "≡", eventually.

> If the user starts at (F) then there is a clear instruction to do that at (G).

What isn't so obvious is that we're now one-level deep in the nesting hierarchy, and that revealing the list of categories at the top level needs clicking the left-arrow near (D). That smaller left-arrow, positioned where it is near the larger "back" arrow for the browser window can be overlooked or dismissed as a UI synonym for "back" rather than "show me the categories". Or, to put it another way, I think it's less reasonable to make the assumption that this is a common or well-understood UI paradigm. The goal should be to help users build a mental map as they go into the documentation hierarchy. Starting them in the middle means they begin without really knowing which way is north.

A couple of approaches suggest themselves. One is to remove the "Getting Started" link at IOTstack GitHub page so the user is forced to "G", perhaps with expanded instructions about navigating on small screens. Another is re-arranging the structure so that the "Home" and "Getting Started" pages are at the same logical level, thereby removing the need to go "up" one level to discover the categories.

Of the two, I think removing "A" is probably the simplest and most rigorous:

* GitHub: there is documentation, here is the link ->
	* Wiki Home:
		* this is how you navigate the doco
		* here's a link to Getting Started material ->

**Comment by ukkopahis** [comment]
I tried to get it all perfect in my big pull-request, but clearly there's always room for improvement.

I like the idea of having "Getting Started" as a top-level page. Originally there were way too many, so I moved them all into Basic_setup. But one more top-level item wouldn't look that bad:

![image](https://user-images.githubusercontent.com/95980324/159469502-695671d2-9927-4d15-9693-52504014865d.png) 
![image](https://user-images.githubusercontent.com/95980324/159469859-056b81d0-e4ae-402d-afcd-bee4fc8cff27.png)

Downsides:
* "Getting started" being inside "Basic_setup" means all the other setup pages (D) are much easier to find. I think this is a case of "Make one thing easier but another thing harder".
*  I think six top-level tabs is starting to decrease clarity&usability. An expert also think that [less than six is important](https://www.nngroup.com/articles/mobile-subnavigation/), at least for subnavigation. Global navigation is [more of a mixed bag](https://www.nngroup.com/articles/killing-global-navigation-one-trend-avoid/).

Implementation would be very easy:
* move docs/Basic_setup/index.md to docs/Getting-Started.md
* mkdocs.yml: Add redirect "Basic_setup/index.md: Getting-Started.md" (and remove the current inverse redirect)

Other improvement ideas:
* Wiki Home and Getting started pages could be merged? 
* Add a site-index page where every page is listed. Implemented using [this plugin](https://github.com/Andre601/mkdocs-pagenav-generator). Add link to it in the middle of the bottom-bar (currently with only prev- and next-links).
* Rename "Basic setup" to "Setup"? Or maybe Configuration? I'm bad at naming things. (But I've found how to easily have a custom non-alphabetical ordering for the navigation tabs)
