### ISSUE TITLE
Could you add Chronograph?

### ISSUE THREAD

**Issue by fpro123** [SensorsIot/IOTstack#55]
Hi, I'm missing Chronograph in your stack. Could you add it?

**Comment by Slyke** [comment]
Will check it out and see how it will fit.

**Comment by Willem-Dekker** [comment]
@fpro123 is this the right container? https://hub.docker.com/_/chronograf

**Comment by fpro123** [comment]
Hi,

That seems right.

Thanks



man. 15. jun. 2020 23.27 skrev Willem Dekker <notifications@github.com>:

**Comment by ukkopahis** [comment]
Chronograph has been added by #397. Scheduling this issue to be closed.
