### ISSUE TITLE
Make README.md the documentation main page

### ISSUE THREAD

**Issue by DIYtechie** [SensorsIot/IOTstack#58]
The current main page https://sensorsiot.github.io/IOTstack/ is outdated and much more complicated than needed. The README.md text or similar would be better for the main page. Perhaps a youtube thumbnail would be nice as well, but that is a minor thing.

Keep up the good work! :)

**Comment by Slyke** [comment]
@Willem-Dekker was handling a lot of the documentation earlier, but I'll do a full review of it once I've done the new menu if he can't get around to it before then.
