### ISSUE TITLE
HTML issues on link 

### ISSUE THREAD

**Issue by kiteloopdesign** [SensorsIot/IOTstack#599]
On https://sensorsiot.github.io/IOTstack/Containers/InfluxDB/ , clicking on this guy makes browser show HUGE fonts. Seems something is funny on that link

![image](https://user-images.githubusercontent.com/17339330/189686344-218e47c4-e93e-4124-a628-b117c1c10411.png)

https://sensorsiot.github.io/IOTstack/Containers/InfluxDB/authentication

Tried on linux both with firefox and chromium, same unreadable content

Thanks

**Comment by Paraphraser** [comment]
Thanks for reporting this. I have put in a pull request to fix it.
