### ISSUE TITLE
Promethius config

### ISSUE THREAD

**Issue by SimonMcN** [SensorsIot/IOTstack#620]
I think that the file ./volumes/prometheus/data/config/config.yml may be incorrect but I leave it to your judgement.

I think that cadvisor needs to be the name of the container, in this case prometheus-cadvisor.  I have made the changes below and they all now show as UP in my local instance @  http://iotstack:9090/targets

scrape_configs:
  - job_name: "iotstack"
    static_configs:
      - targets:
        - localhost:9090
        - cadvisor:8080
        - nodeexporter:9100
        - prometheus-cadvisor:8080
        - prometheus-nodeexporter:9100

**Comment by Paraphraser** [comment]
I believe you are correct. I am going to submit some pull requests to deal with this. Thanks for reporting it.
