### ISSUE TITLE
Incorrect condition checking Docker version

### ISSUE THREAD

**Issue by gbudge** [SensorsIot/IOTstack#728]
https://github.com/SensorsIot/IOTstack/blob/790e83727414eca03079b76de37831bc496f2a14/install.sh#L190C11-L190C11

This does not require the ! In the variable evaluation.

PR: https://github.com/SensorsIot/IOTstack/pull/729

**Comment by Slyke** [comment]
Nice spot!

**Comment by Slyke** [comment]
I've merged the changes.
