### ISSUE TITLE
Disk writes

### ISSUE THREAD

**Issue by dannutu** [SensorsIot/IOTstack#86]
Hi & thank you for putting IOTstack together!

I noticed that right after installing a small set of IOTstack containers (i.e. portainer, node-red, influxdb, grafana, eclipse-mosquitto, pi-hole, rtl_433 to mqtt) on a fresh raspbian OS there are quite frequent writes to the disk on an otherwise completely idle pi. Over 24 hours these writes amounted to some 5 GB, which go towards shortening the life of the SD card or SSD. I was wondering if you could offer any hints to limit these writes? Are they really necessary considering the system is completely idle otherwise?

I've tried to identify the "hot file(s)" but I got nowhere so far (I could not get sysdig to work due to some compilation errors when building dkms and I didn't have time to troubleshoot it further; sysdig docker container also throws some errors so no luck with that either).

Many thanks!
Dan

**Comment by dannutu** [comment]
Any idea how to trace these disk writes? I left the rpi idle for 6 days and iostat is showing 28 GB written to sda although df is not showing a decrease in free disk space, so I suppose some file(s) is/are written over and over. There is no swap configured (no swap partition and no swap file).

**Comment by Slyke** [comment]
Hey @dannutu , try turning  off swap space. It's in the menu, but you can also run these 2 commands:
```
.scripts/disable_swap.sh disableswap
.scripts/disable_swap.sh uninstallswap
```

If you checkout the `.scripts/disable_swap.sh` file, you can see how to do manually.

**Comment by dannutu** [comment]
I did mention above that there is no swap configured :)

**Comment by Paraphraser** [comment]
Have you tried this?

```
$ sudo apt install iotop
$ sudo iotop
a
```

The "a" puts iotop into accumulation mode. The biggest writers tend to bubble to the top (at least they do on my system). I get lots of instances of influxd and dockerd which is what I expected, although I hadn't fully appreciated how many separate instances of those were being spawned all the time.

Most of my IoT devices go MQTT->NodeRed->Influx. Some use SQLite but those are sporadic so it isn't surprising that they don't show up in iotop. Probably the biggest surprise in my output was PiHole which seems quite chatty (logs, presumably). My RPi4 is running on SSD so I'm not particularly concerned about writes - I'd be a lot more worried about minimising writes on an SD.
